# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dpotsch <poetschdavid@gmail.com>           +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/21 13:23:49 by dpotsch           #+#    #+#              #
#    Updated: 2025/01/08 14:42:12 by dpotsch          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

TARGET_EXEC := philo

SRCS = srcs/philosophers.c \
       srcs/argument_utils.c \
       srcs/ft_atoi.c \
       srcs/init_philo.c \
       srcs/philo_handler.c \
       srcs/philo_life.c \
       srcs/philo_life_utils.c \
       srcs/philo_monitoring.c \
       srcs/philo_state.c \
       srcs/philo_utils.c \
       srcs/time_utils.c \
       srcs/mutex_utils.c

-include ../Makefile
-include ../testing/Makefile
