# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dpotsch <poetschdavid@gmail.com>           +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/21 13:23:49 by dpotsch           #+#    #+#              #
#    Updated: 2025/04/02 09:14:25 by dpotsch          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MAKEFILE = Makefile

TARGET_EXEC := philo_bonus

SRCS = srcs/philosophers.c \
       srcs/close_semaphores.c \
       srcs/error_handler.c \
       srcs/utils/ft_itoa.c \
       srcs/utils/ft_strjoin.c \
       srcs/utils/philo_utils_1.c \
       srcs/utils/philo_utils_2.c \
       srcs/utils/time_utils.c \
       srcs/utils/argument_utils.c \
       srcs/utils/sem_value_utils.c \
       srcs/utils/sem_utils.c \
       srcs/utils/thread_utils.c \
       srcs/utils/void_ptr_wrapper.c \
       srcs/parse_arguments.c \
       srcs/init_philo_2.c \
       srcs/init_philo.c \
       srcs/init_semaphores.c \
       srcs/philo_free.c \
       srcs/philo_life.c \
       srcs/philo_life_utils.c \
       srcs/philo_life_utils_2.c \
       srcs/philo_monitoring.c \
       srcs/sim_monitoring.c \
       srcs/start_philo_processes.c \
       srcs/start_philo_threads.c \
       srcs/philo_state.c \
       srcs/wait_utils.c

-include ../colors.mk
-include ../general.mk
# -include ../testing/Makefile
